// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Models.Data;

namespace WebApplication3.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20210415043920_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication3.Models.Customer_Profile", b =>
                {
                    b.Property<int>("Customer_number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Game_point")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Customer_number");

                    b.ToTable("Customer_Profile");
                });

            modelBuilder.Entity("WebApplication3.Models.Game_mall", b =>
                {
                    b.Property<int>("Game_number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Game_category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Game_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Listing_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Unit_price")
                        .HasColumnType("int");

                    b.HasKey("Game_number");

                    b.ToTable("Game_mall");
                });

            modelBuilder.Entity("WebApplication3.Models.Order", b =>
                {
                    b.Property<int>("Order_number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Customer_ProfileCustomer_number")
                        .HasColumnType("int");

                    b.Property<int>("Customer_number")
                        .HasColumnType("int");

                    b.Property<DateTime>("Order_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Order_number");

                    b.HasIndex("Customer_ProfileCustomer_number");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("WebApplication3.Models.Purchase_quantitycs", b =>
                {
                    b.Property<int>("Order_number")
                        .HasColumnType("int");

                    b.Property<int>("Game_number")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Order_number", "Game_number");

                    b.HasIndex("Game_number");

                    b.ToTable("Purchase_quantitycs");
                });

            modelBuilder.Entity("WebApplication3.Models.Order", b =>
                {
                    b.HasOne("WebApplication3.Models.Customer_Profile", "Customer_Profile")
                        .WithMany("Orders")
                        .HasForeignKey("Customer_ProfileCustomer_number");
                });

            modelBuilder.Entity("WebApplication3.Models.Purchase_quantitycs", b =>
                {
                    b.HasOne("WebApplication3.Models.Game_mall", "Game_mall")
                        .WithMany("Purchase_quantitycss")
                        .HasForeignKey("Game_number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Order", "Order")
                        .WithMany("Purchase_quantitycss")
                        .HasForeignKey("Order_number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
